global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-producer'
    static_configs:
      - targets: ['producer:8000']

  - job_name: 'spark-consumer-inference'
    static_configs:
      - targets: ['spark-consumer:8001']
      
remote_write:
  - url: "http://influxdb:8086/api/v2/write?org=ics-org&bucket=ics&token=admintoken123"
