apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
  namespace: ics
  labels:
    app: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
      annotations:
        promtail_scrape: "true"
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ["sh", "-c", "until nc -zv kafka 9092; do echo 'waiting for kafka'; sleep 1; done"]
      containers:
        - name: spark-consumer
          image: henrikberenyi/model:latest
          imagePullPolicy: Always
          args: ["inference.py"]
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: SERVICE_NAME
              value: spark-consumer
            - name: LOG_LEVEL
              value: INFO
          resources:
            limits:
              nvidia.com/gpu: 1
