name: Build and Push Docker images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Verify LFS files
        run: git lfs ls-files

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push model image
        uses: docker/build-push-action@v4
        with:
          context: model/
          file: model/Dockerfile
          push: true
          tags: |
            henrikberenyi/model:latest
            henrikberenyi/model:${{ github.sha }}

      - name: Build and push producer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: producer/Dockerfile
          push: true
          tags: |
            henrikberenyi/producer:latest
            henrikberenyi/producer:${{ github.sha }}

      - name: Build and push kafka-to-influx image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: consumer/Dockerfile
          push: true
          tags: |
            henrikberenyi/kafka-to-influx:latest
            henrikberenyi/kafka-to-influx:${{ github.sha }}
